version: "3.9"
   
services:
    web:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
            - rabbitmq
    db:
        image: postgres
        volumes:
            - ./data/db:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - PGDATA=/tmp
        ports:
            - "5432:5432"
    celery:
        build: .
        command: celery -A core worker -l INFO
        volumes:
            - .:/code
        depends_on:
            - web
            - rabbitmq
    rabbitmq:
        image: rabbitmq:3.7-alpine
