# Generated by Django 3.2.4 on 2021-06-17 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_webhook', '0002_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('sent_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot_webhook.user')),
            ],
        ),
    ]
