# Generated by Django 3.2.4 on 2021-06-18 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot_webhook', '0003_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sent_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot_webhook.bot'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sent_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='bot_webhook.user'),
        ),
    ]
